# Generated by Django 4.1.7 on 2023-03-22 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departmentmaster',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('created_by_date', models.DateField()),
                ('created_at_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SubDepartmentmaster',
            fields=[
                ('sub_department_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_department_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('created_by_date', models.DateField()),
                ('created_at_date', models.DateField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empweb.departmentmaster')),
            ],
        ),
    ]
