# Generated by Django 4.1.7 on 2023-03-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdepartmentmaster',
            name='sub_department_name',
            field=models.CharField(max_length=110),
        ),
    ]
