# Generated by Django 4.1.7 on 2023-03-23 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empweb', '0002_alter_subdepartmentmaster_sub_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('join_date', models.DateField()),
                ('created_by_date', models.DateField()),
                ('created_at_date', models.DateField()),
                ('updated_at', models.DateField()),
                ('updated_by', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empweb.departmentmaster')),
                ('sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empweb.subdepartmentmaster')),
            ],
        ),
    ]
