# Generated by Django 4.1.7 on 2023-03-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empweb', '0004_alter_departmentmaster_created_at_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdepartmentmaster',
            name='created_at_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
