# Generated by Django 4.1.7 on 2023-03-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empweb', '0005_alter_subdepartmentmaster_created_at_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='created_at_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
